import React from "react";
import Head from "next/head";
import Layout from "../components/Layout";

export default function Chapter() {
  return (
    <Layout
      prevPageHref="/chapters/trial-and-better"
      nextPageHref="/epilogue"
      className="w-full">
      <Head>
        <title>Behind the Scene</title>
      </Head>
      <section className="h-screen bg-[#fffef7] text-[#892b2b] text-2xl py-24 flex flex-col justify-center px-16">
        <h1 className="text-5xl font-bold">&quot;</h1>
        <h1 className="text-[#fffef7] text-5xl font-black" style={{WebkitTextStroke: '1px #892b2b'}}>Enriching our education to serve its <br/>purpose:</h1>
        <h1 className="text-6xl font-black mt-16">For the betterment of humanity.</h1>
      </section>
      <section className="bg-[#892b2b] text-white text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Wei Shyy</h1>
        <h3 className="text-lg">President of HKUST, Sep 2018 - Oct 2022</h3>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">I have always believed that education shares the same purpose as technology: to ameliorate humanity. We strive to lead our students to understand the needs of human beings and the means by which they could be met, but there has always been a gap between what we do in our programs and what deliverable solutions we produce that actually make the difference. SIGHT proposes a visionary methodology that elegantly bridges this gap, so it was not at all a hard decision to offer SIGHT
my full support. From bringing our students to empathize with real world problems through site visits to delivering the fruit of their hard work to those they serve, I am very proud of SIGHT and HKUST for pioneering a delivery framework that addresses the comprehensive, human-centered nature of education.</p>
          <p>I am delighted to learn that SIGHT has been successful in attracting students of different backgrounds and breaking boundaries drawn by generalizations. SIGHT does not only bring together students of different Schools and year levels, but also people of different cultures and educational backgrounds. The rigor of SIGHT pushes students from programs with less focus on STEM to get comfortable with technology and students of STEM background to nurture their social and communication
skills. On a SIGHT project you can stick to your strengths and sharpen them, or
you can choose to venture into a foreign field - it is completely up to you and your teammates. The interactions that SIGHT fosters are more than means for our students to learn from each other. They also drive our students on a collective journey of self- actualization and the development of a humanistic mind.</p>
          <p>At the heart of what SIGHT does is synergism. Given the diversity in our students, advisors and partners, we are not trying to simply tick all the boxes. Instead,
we believe in their resonance, that they can find common grounds with their empathies, talents and personalities, to create something greater. In fact humanity is facing increasingly complex challenges that require collaboration between different organizations and disciplines to tackle, and I am sure that anyone who has experienced SIGHT would agree with me. The way our Common Core curriculum streams courses makes it an arduous task to demonstrate synergy across different fields of expertise. Fortunately, our experiential learning programs like SIGHT offer extremely rewarding and insightful experiences for those with zest and dedication.</p>
          <p>In my eyes, three virtues make up the bedrock of SIGHT&apos;s spirit: perseverance, open- mindedness and humility. Our students are challenged by numerous obstacles along the way, but like the way things work in sports, repeated effort is really a prerequisite of success of any form. To tackle these challenges you would need to be open to
a variety of approaches and possibilities, and most importantly, be mindful of the differing perspectives of your peers. Last but not least, keep in mind that you can learn from anything, anywhere. The aircraft is a multi-generation effort that stemmed from the study of nothing more than something that is always around us - birds. With these three virtues, I am sure that future generations of SIGHT students will carry the legacy and be strong advocates of their motto, <strong>&quot;Simple Technology, BIG Difference&quot;.</strong></p>
        </article>
      </section>
      <section className="h-screen bg-[#15216a] text-white text-2xl py-24 flex flex-col justify-center px-16">
        <h1 className="text-6xl font-bold">&quot;</h1>
        <h1 className="text-white text-6xl font-black">It is through SIGHT,<br/> that I see with students, learn with students <br/>and serve with students.</h1>
      </section>
      <section className="bg-[#fffef7] text-[#142a44] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Ying Chau</h1>
        <h2 className="font-medium text-lg">Founder and Director, SIGHT at HKUST, 2014 - present</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">Under the near-40 ̊C sun, one could see the sweat on the students&apos; backs as it soaked through their shirts. The group had just pulled an all-nighter, and they were now explaining how their creation works to the medical team serving the slums in Phnom Penh, Cambodia. Students from different majors pulled together to construct their electronic medical record system, over months of development and testing. They still worried that their system would not be accepted by the local residents,
but relief is palpable when one of the residents spontaneously made way to the fingerprint sensor by themselves to retrieve their medical record. At the other end of the site, other students were running an open air health seminar. While language was still a barrier, thanks to the translation of our local partner, the students and residents were mingling, sharing what ails them, in health and in life. Each and every one of the students wore their blue SIGHT t-shirts, with “Simple Technology, BIG Difference” emblazoned on the back. This moment from the Cambodian trip with the MedEasy Project Team is still etched in my mind. Each SIGHT project comes with such cherished memories. Every time I witness students’ selfless dedication to their projects, their passion to change the world for the better, I find myself so proud of them. And not just pride, but also newfound respect, as well as gratitude for the hope they are bringing to the future.</p>
          <p>Over the years, taking students all over the world to implement projects was to leverage creativity and knowledge to serve society. But along the way, it became more of a humbling experience. In the mountains of Guizhou, under a starry nightscape and in a valley lit up with fireflies, I saw the beauty that lies beyond the material world. In the countryside of Cambodia, a local community leader built an oasis with scant resources, highlighting their tenacity and wisdom. And through video conferencing this year, I got to meet ethnic minorities in north-eastern Myanmar, who were displaced due to war, but still brimming with hope and unfading smiles on their faces. It is hard not to admire their resolve!</p>
          <p>I am a person of faith, and I truly believe SIGHT is a godsend. It is through SIGHT, that I see with students, learn with students and serve with students.</p>
        </article>
      </section>
      <section className="h-screen bg-[#fffef7] text-[#412312] text-2xl py-24 flex flex-col justify-center items-center px-16">
        <h1 className="text-6xl font-bold w-full">&quot;</h1>
        <h1 className="text-[#fffef7] text-8xl font-black" style={{WebkitTextStroke: '2px #142a44'}}>Learning is all about </h1>
        <h1 className="text-[#412312] text-8xl font-black">experience</h1>
        <h1 className="text-[#fffef7] text-7xl font-black" style={{WebkitTextStroke: '2px #142a44'}}>rest is just information.</h1>
      </section>
      <section className="bg-[#bfab95] text-[#412312] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Anirban Mukhopadhyay</h1>
        <h2 className="font-medium text-lg">Faculty Advisor</h2>
        <h2 className="font-medium text-lg">Associate Provost (Teaching & Learning), Sep 2020 - Jan 2022</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">With a balanced amalgamation of innovation, training and real-life implementation, SIGHT offers a unique and exciting platform for students to get acquainted with
the ground reality. To me, the distinguishing feature for SIGHT is its clearly laid out multidisciplinary focus and the sheer institutional backing provided by committed members of SIGHT, including the instructors, advisors, leaders to name a few. The strong foothold that SIGHT has made for itself in the past 7 years is a result of its commitment, and passion towards experiential learning that came out in an effort- intensive, yet, effective manner. I look forward to seeing more courses at UST that can look up to SIGHT and incorporate the virtues of it.</p>
          <p>Students these days are really afraid of failure, but in life you fail more often than you succeed. If you keep yourself in an environment where everything is within reach, it would be an artificial cocoon you will be putting yourself in which is not preparing you for life, for jobs, for anything. You are constantly being selected throughout your life and it is up to you to take up opportunities that facilitate your own character development. And this is emphasised in the value of SIGHT - it is the process of personal growth more than the product created itself. SIGHT really teaches you about yourself and constantly puts you in a position to question your assumptions as you put yourself in others’ shoes and connect with the real world.</p>
          <p>We feel lucky to be able to provide our students with ample resources such that the only limiting factor in their development is their imagination itself. At SIGHT, students from multiple, and often complex, backgrounds come together and pool in their knowledge for a shared objective, challenging them to push their boundaries and be the best version of themselves. In the near future, we are going to accommodate topics related to humility, empathy and mental toughness in the common core curriculum because we recognise the importance of instilling these traits from the beginning of their journey into adulthood. What you are teaching and how you are teaching needs to be constantly reshaped as there are technological advances every now and then - so amidst the uncertainty of the future, we only strive to bestow
the right attitude towards learning and constantly remind ourselves of the ultimate purpose we serve: for the betterment of humanity.</p>
        </article>
      </section>
      <section className="bg-[#fffef7] text-[#134d4d] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Marshal Liu</h1>
        <h2 className="font-medium text-lg">Faculty Advisor</h2>
        <h2 className="font-medium text-lg">Food gerontechnology - Feed You Well, Zi Saam Dim Sum</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">There are lots of problems arising every day. Hong Kong students, both primary and secondary school students, often lack the opportunity to be exposed directly to these problems. Social issues are included in class discussion e.g. during Liberal Studies lessons, but simply learning is different from getting involved personally and coming up with solutions. The emotional attachment, which is also the human element, makes things happen differently. Luckily, SIGHT is present in HKUST for connecting students with the world, equipping them with problem-solving and communication skills.</p>
          <p>SIGHT is different from any other programmes in UST. As an experiential learning course, it offers a well-designed but customised course design to students, depending on different project teams&apos; needs. Usually, project milestones are set according to students&apos; pace and the teaching team’s expectation. Simultaneously, students have to be learning-driven to identify and acquire useful skills for the project themselves. I believe the flexibility given have made the learning space more relaxing and uplifting for the students.</p>
          <p>SIGHT also emphasizes a lot on connection with people. When working on the projects, faculties, advisors and partners constantly provide feedback to teams
during internal check, while students should continuously communicate with other project stakeholders like the end-users of their solution to check on the feasibility and effectiveness of their ideas. The projects are not only about what the students believe is good, but also other external parties’ input.</p>
          <p>Another magical point about SIGHT, is the way it encourages cross-cultural exchange. It is common for students from similar cultural background to form their own social circle, but you need a global team to deal with global health issues.
In SIGHT, students from diverse background come together and work on the big tasks. Different insights and perspectives are brought up, which adds more spark to the discussion too. Good and interesting collaboration among students are often observed. In general, students are open-minded and love learning from their peers. Cultural diversity is much embraced in SIGHT.</p>
          <p>Having previously been involved with the anemia project team, I am also impressed by how passionate and dedicated the SIGHT students are. Under the pandemic, everything has to be switched online. The team managed to work well and support each other, despite not having a relevant knowledge background. Things were not always smooth, but the team also had a strong mentality when facing failures from their prototypes. Their passion has fuelled them throughout the hard times, and their experience would be very meaningful when they look back at what they have achieved. This is one of the special features that SIGHT students possess.</p>
          <p>Without a fixed course syllabus, SIGHT looks beyond GPA. Students learn from real-life, learn from application, learn from the world, with empathy. Students would also go through series of personal development during the course. There might be failures at times, but students have learnt to be tough. I hope that in future, students could put more emphasis on ECAs activities like SIGHT, be trained and cultivated to become good society leaders.</p>
        </article>
      </section>
      <section className="bg-[#134d4d] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Vincent Li</h1>
        <h2 className="font-medium text-lg">Faculty Advisor</h2>
        <h2 className="font-medium text-lg">Lavatory Management System, CollaBox, Malaria Prevention</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">It is my pleasure to write about my memories during the last five years as a SIGHT advisor and I am happy to see SIGHT has experienced their six years journey. I joined SIGHT in 2015 when I commenced my humanitarian services with Medecins San Frontiers (Doctor Without Borders) as a field worker. I have engaged in missions in various war zones and pandemic areas, like Afghanistan, Cambodia, Nigeria, India, Zimbabwe and Sierra Leone. I was responsible for designing and building new hospitals in the affected areas; and providing technical supports to the front line medical operations. My experience in Samaritans Befrienders (counseling people who are suicidal) also facilitates me in assisting my colleagues in the field who are stressed and frustrated. I hope my past experience in helping others can provide guidance to SIGHT students working on humanitarian projects.</p>
          <p>I have made a number of presentations about my missions for SIGHT students. I was happy to see students were quite enthusiastic about the humanitarian operations
in these problematic countries. Some of them showed their interest of participating in similar missions in the future. My advice is them is to have consensus from their family as the tasks may be risky. Also, we have to keep ourselves in good physical and mental states to work in those areas.</p>
          <p>In my role as an advisor, I have supervised a number of student projects targeting
on resource-limited communities and tackling issues within their settings. In the project “Improving hygiene and health education for inhabitants in rural Cambodia”, students have shown their care and passion to the people in the rural area of Cambodia. The objective was to educate the local students about sanitary issues and help them initiating a self-sustaining business model to collect funds for similar future projects. The students proposed good thoughts in technical contents about the
soap workshop and the hygiene training program. We did give some ideas about the business model which could be done effectively, together with the way to sustain the business. I understood that students implemented the project well and achieved their expected results.</p>
          <p>Groups of students worked on projects to develop assistive technology for students with special needs at Caritas Lok Kan School in Hong Kong. SIGHT students have opportunity to contribute their engineering knowledge to the disabled children in the school. They developed a system to monitor the toileting habit of the children using RFID technology. Students took initiatives to test their prototype in the school and overcome various technical problems. We provided suggestions for the selection of components and the design of the overall system. Despite the fact that further improvement could be done on the developed technology, the administration of the school has got the insight and concepts from the students in this project and used them to assist their daily operations.</p>
          <p>It is nice to see HKUST student are making contribution to the society and they offer technological solutions to the problems which are experienced by the underprivileged. I am happy to be a SIGHT advisor and I will continue sharing my experience in humanitarian operations with the students, as well as providing guidance to their projects.</p>
        </article>
      </section>
      <section className="bg-[#382656] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Prof. Rhea Liem</h1>
        <h2 className="font-medium text-lg">Faculty Advisor</h2>
        <h2 className="font-medium text-lg">CollaBox, Environmental Awareness in Sri Lanka</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">Not long after I joined HKUST, I noticed a large SIGHT banner near the Piazza. Intrigued, I started searching for more information about what I thought would be an interesting and meaningful program (and of course, it is). Well, you see, “service” and “social awareness” have been a big part of my upbringing. I spent half of my pre- tertiary education in a school where “I will serve” is the motto and guiding principle. Hence, naturally, SIGHT’s vision and mission are very close to my heart and I wanted to know whether I could contribute. Yet, I didn’t make any efforts to join at that time for several reasons. First, I had bigger fish to fry, i.e., to survive in my new job (highly important!). Second, with my aerospace engineering background, I thought there was no room for me to contribute. Lo and behold, one day I received an email from none other than Prof. Ying Chau herself—the esteemed founder, director, queen bee of SIGHT—with an invitation to be a faculty advisor for SIGHT. She assured me that my aerospace engineering background could “somehow be useful to SIGHT.” It was in 2018, and the rest is history. Since then, I have supervised four SIGHT projects and am still immensely enjoying my role and involvement.</p>
          <p>Being a faculty advisor for SIGHT reminded me of four things—things that should
be obvious but are often forgotten. First, everybody has a place to contribute to solving real problems in the society. We do not need a medical-related background to help bring tangible, meaningful, and impactful global health solutions. Our genuine intention will guide us to find that specific corner where we can contribute. Second, diversity indeed brings quality. Each SIGHT project group typically comprises students, faculty advisors, and other members with different background—in terms
of academic, gender, culture, personality, interests, etc. Finding a unique solution for a unique problem requires bringing different perspectives on the table, which is only possible with a heterogeneous team. Third, one of the biggest roles of a teacher is to teach students how to think and learn, instead of just imparting knowledge. Even when the project is beyond my area of expertise, I can always ask the right questions, challenge the students, and help with the project management aspect of it. In other words, as a faculty advisor, I do not necessarily have to bring solutions to the table, but I can always help students navigate the challenges and difficulties such that they can formulate the technological solutions themselves. Fourth, university is truly a place for continuous learning, which also applies to teachers. In the past few years, I have learned a lot from all members of SIGHT, including staffs, other faculty advisors, project partners, and also students.</p>
          <p>Being part of an academic community, we are constantly reminded about the importance of academic excellence. Yet, we need to remind ourselves that academic excellence is necessary but not enough. It is important for us to be aware of the needs of the society and find ways, within our capacity, to help. SIGHT provides an avenue for teachers and students not only to sharpen this social awareness, but also to act upon it. I believe that the positive impact of SIGHT will extend beyond what SIGHT students deliver to society now—it covers what they will deliver in the future and the influence they will pass to the next generation. Education, after all, is always about paying it forward.</p>
          <p>To me, personally, serving in SIGHT has been an honor and a gift. Thank you all. SERVIAM.</p>
        </article>
      </section>
      <section className="bg-[#fffef7] text-[#382656] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Francis Lo</h1>
        <h2 className="font-medium text-lg">SIGHT Mentor</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">I came to SIGHT with a mindset developed from a career in management consulting. I remember my initial skepticism during my first encounters with people from SIGHT – they were full of ideas, but my management consulting mind told me 90% of
their ideas were utterly unviable. However, as I watched these people realise their ideas – many in a form different from what they originally intended and not without numerous failures – I realised my first instincts were wrong, and I am grateful for that. SIGHT showed me a world of possibility.</p>
          <p>There were no shy people at SIGHT. Everyone I met at SIGHT basically told me the same thing: “I want to be here”. These are people from all over the world, with different mindsets, from different walks of life. There was huge diversity, but they were united in their journey and their beliefs.</p>
          <p>At SIGHT, the journey our people went through was emotionally challenging - prototyping with high hopes, struggling with conflicting ideas and mid-term pressure at the same time, rolling up their sleeves and satisficing somewhere, undoing it
and producing something much better at right before the final presentation. The moments that impressed me most were when they paused and asked questions: they debated the “what” and “how” and asked, “for whom?”. I saw a team developing
a Joystick Keyboard to help Mucopolysaccharidosis (MPS) patients, recognizing the patients&apos; needs for such a device to express their talents at work. I saw a team using locally available seeds as an economical means to cleanse polluted water, so that people in poor villages could lead more fulfilling lives. Their journeys were fraught with failure, but they learned from it, and not only did failure not set them back – it propelled them forward.</p>
          <p>To me, SIGHT is doing exactly what university education is supposed to. It provides a habitat for young adults to turn their beliefs and their visions into reality. No matter how unrealistic I thought their ideas were, the SIGHT teams continued failing forwards and created paths towards solutions in their own ways. My experience at SIGHT informed both my perspective and my journey with my own start-up, Dot Dot Fire – I have learnt to fail forwards relentlessly, and my belief in creating inspirational and ethical education through games has blossomed.</p>
          <p>The spirit of SIGHT is similar to HKUST in its infant years, as the University built
itself bit by bit into the world ranking institution it is today. In particular, SIGHT reminds me of Prof. Kung Shain-Dow, Professor in Biology, Dean of Science and Vice President for Academic Affairs in the period of 1991-2001, whom I had the privilege of working with during my time at the Students’ Union. Whilst Professor Kung was never hungry for the spotlight, he was instrumental to the University’s evolution into the living ecosystem it is today, where people connect to excel, and our students are encouraged to take charge and fail forwards. The soul Professor Kung worked hard to nurture is well and alive in the HKUST community, and I believe it is embodied and deeply felt by the culture and people at SIGHT.</p>
          <p>With this, I dedicate my humble contribution in SIGHT to Prof. Kung Shain-Dow, a gentleman, scientist, educator, and entrepreneur whose legacy lives on though he has departed.</p>
        </article>
      </section>
      <section className="bg-[#c56e56] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Yuki</h1>
        <h2 className="font-medium text-lg">Former SIGHT Teaching Associate</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">I am Yuki. I joined SIGHT as Teaching Associate in May 2014 and worked until 2016. Now I live in another city and am a mother of a three year-old. Back then SIGHT was just founded. We started small. There were 8 student members in Fall 2014 and 12 in Spring 2015. I was the only full-time staff for the first year. Looking back, the three semesters I worked in SIGHT was like “prototyping”. We didn’t know what exactly the program should look like. But we kept trying and learning from it. Things were new and chaotic. But it was also this period that allowed us to lay down the program framework and made us confident that it could work.</p>
          <p>I dug out SIGHT files from my old laptop. And I am still kind of amazed by how much we pulled through together and how far we pushed ourselves. Students spent way more hours
on projects than course credits asked for. They coped with complexity, time constraints, and expectations that were incomparable to any academic exam. I myself must quickly shift from a postgraduate to a staff handling both teaching and logistics, responsible to both students and partners. Things can be stressful when they are intense and you care. I remember I threw up the first night I led a team to Cambodia, and it was not because of the hygiene there. But this experience also turned out to be the most worthwhile part of SIGHT. That’s why the students were thrilled when they saw their product finally being touched and used, and I felt proud witnessing this. At the end, it is what we are most dedicated to that makes us most proud of. No shortcuts.</p>
          <p>But sometimes, things just don’t work out even when we work hard and care. I personally felt grateful to the first students and partners, who stayed with the program when it barely started. Part of my pressure was from the thought that I badly wanted them to succeed. But the thing is, we always emphasize SIGHT projects are unique because they are real, while reality means no guarantee for outcome. As teaching staff, it is my job to give my full support. But if I try
too hard, the learning experience may not be real any more. So where is the line between my responsibility and the students&apos;? As a parent, I find myself in a very similar situation. I believe the current teaching team already has a better answer. Taking the result properly should be a quality equally important as persistence.</p>
          <p>Finally, this is my favorite photo of SIGHT. We step into the unknown with friends and determination to change for the better. May we all not forget why we started the journey.</p>
        </article>
      </section>
      <section className="bg-[#a0b98c] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Fernando</h1>
        <h2 className="font-medium text-lg">SIGHT Leader</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">Having spent 4 years at SIGHT, I am quite qualified to say SIGHT is constructed by selfless efforts and very voluntary. I joined SIGHT camp just to discover new things, with
no expectations of the program. The application process involved a group interview with a problem-solving task. The teaching team was interested in how we would go about solving the problem, rather than the result itself. From then, I have always seen SIGHT as a creative space and a very exciting project to be part of. It gathers like-minded people to look at various health challenges, and eventually welds ideas and solutions. It helps people, it improves the wellbeing of communities, what more could you ask for?</p>
          <p>On a rather macro scale, SIGHT&apos;s role is the union of disciplines for a social impact. It brings together people of different backgrounds to form interdisciplinary teams, hoping to use technology in a smart way. “Simple technology, BIG difference,” our slogan is really true. Some of the technologies we use might not even fall within our traditional conception of technology, but with innovation and by putting them into the right social context, they can be very powerful.</p>
          <p>SIGHT means a lot to me for two reasons. First, I could bring my unique skillset to play
an impactful role in the team. As a social science student working among engineers and scientists, I forced myself to look at problems in a way my other teammates would not. I pushed forward the inclusion of end users. A way to achieve this is by acknowledging the high degree of context specificity of our projects, which could be easily missed if one becomes overly obsessed with the technology. I think every team should have a social scientist who looks into the political, social and cultural context to make sure we are making real, and not just perceived impact.</p>
          <p>SIGHT also shaped the way I work as a public policy specialist today. SIGHT&apos;s work ethos and perspective aligned very well with how I want my work to be done from a social science angle. We are constantly making sure whatever we are building is actually impactful, which resonates with me really well. Of course, I also got to pick up really cool technical skills and work with really cool people.</p>
          <p>My journey at SIGHT did not stop at MedEasy. As a SIGHT leader, I was able to build internal connections within SIGHT and take part in the learning process of SIGHT itself. One of the most important tasks for leaders is helping new campers arrive at their own ideas without giving them away. The hardest part is letting our experience guide us, but not blind us. Initially we had a fingerprint scanner on MedEasy, but it did not work, so we had to find a replacement biometric. We decided on an iris scanner. which actually worked much better than expected and avoided many problems that would have surfaced with the fingerprint scanner. This story proves that new and untested ideas are not bad, and our existing ideas are not necessarily good. Staying open and allowing things to happen is vital in keeping our projects organic and constantly improving.</p>
          <p>Embracing spontaneity does not mean giving up on thinking entirely. The more sophisticated SIGHT is, the easier it is to be stagnant. It takes constant questioning on everything to keep us on our toes, ready to adopt something better. Is this the right way to approach the problem? Is it the best way to do it? I made a conscious effort of trying to do something different throughout the four years. They say you should leave things in a better state than you found them. I guess that had kept me going, and I think I did make a positive difference.</p>
        </article>
      </section>
      <section className="bg-[#a0b98c] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Vanessa</h1>
        <h2 className="font-medium text-lg">SIGHT Leader</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">There is a story about a caterpillar, being afraid to change until a butterfly encourages him to believe in himself. Eventually, the caterpillar faces his fears, breaks through all the challenges and becomes a butterfly. Why am I bringing this up? Probably because “Vanessa” can be referred as “butterfly” in literary work, but I am still on my way to becoming a “Vanessa”.</p>
          <p>I love things that are dynamic, but I used to hate changes too. During my first year in university, I barely joined any school activities. Peer comparison also stressed me out. Stepping out of my comfort zone to talk to others was such a big challenge. Though, it is often stressed that university is a place to extend your connections and try every possibility. In my second year, I started looking for opportunities, as I did not want to continue wasting my time here, and I met SIGHT.</p>
          <p>“Sounds impactful and I can get my hands dirty here!”. And SIGHT does not disappoint (as always!). As business students, we seldom have opportunities to “make things work”. Our ideas only stay on paper, but it is different in SIGHT. We can interact with our stakeholders directly and implement our formulated solutions, actually creating small changes in the society that makes someone’s life out there easier. I worked on a project for SEN students in Caritas Lok Kan School, in which me and my teammates developed a collaborative game to raise students’ awareness of others, as not all of them are capable of communicating. Perhaps “collaboration” is what we do everyday, what we are not even aware of, but it is something new, a big change to the SEN students. “Think out of the box,” SIGHT let me understand that it should be “think out of their box” when ideating.</p>
          <p>After going through SIGHT Camp and ENGG4930 (and also continuing our project as SIGHT Scholars), I stayed as a SIGHT Leader, not only because I want to be exposed to more projects and ideas given by my peers, but also, the learning environment in SIGHT is comfortable, warm and irreplaceable. Although I studied in EMI secondary school, I had bad language skills and broken spoken English. I tended to stick with locals when having class or doing projects to minimize the language barriers, but there were lots of international students in SIGHT. Things turned out to be great, though, as my teammates were very supportive and patient in listening to me. During the project time, our team had to constantly acquire new skills for developing the game, as none of us had experience in doing so. Endless trials were needed to successfully run the game, but our team spirit fueled everyone to overcome the challenges.</p>
          <p>The friendly teaching team gave us lots of motivation too. They embrace every idea, no matter how crazy they are. Of course we cannot implement possible solutions, but receiving support from them during ideation gives us even more energy to work. As someone who
is afraid of making mistakes, the SIGHT learning environment motivates me to try new ideas. Even if they fail, just have a laugh and try again. Sometimes it might be our fears that disheartens us from achieving, but SIGHT can always cheer me up.</p>
          <p>Simple Technology. Big Difference. We don&apos;t always need fancy solutions to solve world problems, and it is what SIGHT is about. I used to believe that if I can change the world, I
will be having big achievements, and that makes me happy. Reality tells instead, change is relevant, regardless of the scale. Like in my Caritas project, SEN students represent only a small portion of the population, but that does not mean changes made for them are not important or useful. I had a great sense of fulfillment afterwards too. Perspective matters. Comparison is not always the best method to learn and improve. As long as you excel in your own expertise or focus, things will look good.</p>
          <p>SIGHT plays a crucial part in my university life, not just because I love hanging around the lab. It has inspired me to always think and do beyond what I previously believed was the limit. My SIGHT journey has given me more confidence and a stronger mentality. Although now, I am still a caterpillar wandering around the leaves and getting sense of the world. One day, I will break through the cocoon and become a butterfly and soar.</p>
        </article>
      </section>
      <section className="h-screen bg-[#447f7f] text-[#fffef7] text-2xl py-24 flex justify-center items-center px-16">
        <div className="h-24 w-0.5 bg-[#fffef7] mr-8"></div>
        <h1 className="text-5xl font-bold">&quot;SIGHT is my second home and I&apos;ve enjoyed every bit of my time here.&quot;</h1>
      </section>
      <section className="bg-[#fffef7] text-[#447f7f] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Malinda</h1>
        <h2 className="font-medium text-lg">SIGHT Teaching Team - Program Manager</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">I first heard about SIGHT when I was in my final few months of postgraduate studies in HKUST, and I was deeply impressed by what SIGHT was doing and how it applied the student innovation mindset to solve health problems around the world. Once I graduated, I got a chance to join as a SIGHT Teaching Team member.</p>
          <p>Since then, SIGHT is my second home and I&apos;ve enjoyed every bit of my time here. It would be impossible to cover all the memories at SIGHT but I will try my best to summarize the more memorable ones.</p>
          <p>SIGHT uses Design Thinking as an Innovation platform, where students get a chance to understand user needs, develop empathy and create prototypes to solve the needs of the people around the world. At SIGHT we keep students at the center of the learning process, trying to understand their needs and develop programs and workshops to make the whole experience an enjoyable one. We use Design Thinking to innovate new teaching methods for students to enhance the learning process. Students gather every week to brainstorm innovative ideas, develop prototypes as a team and most importantly make human connections with people from diverse backgrounds. Coaching a bunch of people who are motivated to design and innovate is a great fulfillment in my teaching life.</p>
          <p>Implementation trips are one of the main key moments in SIGHT experience. Where we (SIGHT Teaching Team and Students) travel to different project sites to implement the solutions developed by the students. It is a rewarding time for students as well as for the SIGHT Teaching Team, witnessing how initial ideas transform into to prototypes which can lead change the people’s lives. Other than the demanding work, students are enjoying every bit of the moment in trips; cracking jokes, sharing life experiences etc. It is a wonderful opportunity to bond with people and build long term connections.</p>
          <p>The SIGHT Teaching Team consists of people from diverse backgrounds, different personalities but sharing the same mission towards learner-centered education and impact creation through student innovations. Everyone in the team is empowered to propose new ideas and turn them into innovative programs, and also support each other to accomplish the goals. This open and flexible working environment is one of the keys to the success of SIGHT.</p>
          <p>SIGHT has expanded over the years, and it is always great to reflect on what we did, what went wrong, and how we can even improve by looking at the past. This is a great moment for everyone who were involved in the SIGHT journey to look back on what we have done and share the moments of those experiences!</p>
        </article>
      </section>
      <section className="h-screen bg-[#fffef7] text-[#667e55] text-2xl py-24 flex flex-col justify-center items-center px-16">
        <h1 className="text-5xl font-bold">&quot;Amidst the hurricane that was life I found refuge, insights and perhaps even growth in SIGHT.&quot;</h1>
        <div className="h-0.5 w-full bg-[#667e55] mt-4"></div>
      </section>
      <section className="bg-[#667e55] text-[#fffef7] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Joel</h1>
        <h2 className="font-medium text-lg">SIGHT Teaching Team - Instructional Assistant</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">This is a haphazard story on how I found an unlikely home by enrolling in a course on a whim after lunch. After messing up my college credits, I was on my last semester as an extension in HKUST. The usual approach to do this was to take the minimum course load, fulfil whatever requirements that is left, and just cruise your way into an easy finish, all the while looking for a job. Obviously, none of that happened, from the cruising to the job hunting.</p>
          <p>As Don Keefer once said, it all started with &apos;the lunch&apos;. An old high school friend of mine, Thalha, shared excitedly about a ground-breaking course that he took. A course that took him to Cambodia, and let him work on something hands on. It was an instant draw, I didn’t even care about the travel, just the idea that I would get to work on something hands on was beyond enough. Having grown up on a steady diet of Top Gear, there was just something romantic about cuing the A-Team theme and breaking out the angle grinders and power drills. Granted I never had any formal training on any hardware at that point, but all Jeremy Clarkson had were honorary doctorates of engineering and an unlimited supply of jeans, and they did zilch in getting him across the British Channel.</p>
          <p>Then came the fateful interview, which gave me a taste of what was to come. Never was I
so at ease, and had so much fun in an interview. The whole exercise was about helping your partner prepare the perfect gift for their best friend, a task we still use time to time at SIGHT. As much fun as it was though, I would later learn that I almost did not make it through the selection process. The team I had applied for was looking for a mechanical engineer, but I was as close to a mechanical engineer as my imaginary dog is an imaginary cat. There was however a mechanical engineering applicant, so as the team slightly struggled with who to choose, someone thankfully blurted out “Why not both?”, and I was in.</p>
          <p>Fast forward 6 seasons (years) and a movie (year), it had been one wild ride. It was more than anything that I could have dreamed of. I got to live out my best life as a project photographer, capturing genuine heartfelt moments as students gave life to their projects and engage with users, be it in Hong Kong or in some far-flung corners of Southeast Asia. With the Teaching Team, I got to design games and training, from physical ones to virtual ones. Our programs went from just SIGHT Camp to now a catalog that includes a Common Core course. Amidst the hurricane that was life I found refuge, insights and perhaps even growth in SIGHT. I was just lucky enough to know that I am in the good old days before I’ve actually left them. And on that bombshell, it’s time to end (this piece).</p>
        </article>
      </section>
      <section className="h-screen bg-[#fffef7] text-[#29347f] text-2xl py-24 flex flex-col justify-center items-center px-16">
        <h1 className="text-6xl font-bold">&quot;<span className="text-[#fffef7]" style={{WebkitTextStroke: '2px #29347f'}}>Being able to</span> empathize <span className="text-[#fffef7]" style={{WebkitTextStroke: '2px #29347f'}}>is an</span> engineering skill&quot;</h1>
      </section>
      <section className="bg-[#dda746] text-[#29347f] text-2xl flex flex-col items-center py-24">
        <h1 className="font-black text-5xl">Kris</h1>
        <h2 className="font-medium text-lg">SIGHT Teaching Team - Assistant Software Engineer</h2>
        <article className="text-xl w-4/5 mx-auto flex flex-col space-y-10">
          <p className="first-letter:text-4xl">At SIGHT, we bring real life struggles and challenges of underprivileged communities and everyday people to our students. In a semester or two, these students begin as if they are a blank piece of paper to incubate their ideas and create solutions for the real world in a very short period of time. However, these achievements mostly did not come from their intellect, but from their ingenuity to listen and pay close attention to the details of what people really need. It was no easy journey for the students to embark on. During the 14 weeks of SIGHT Camp, the students went from knowing nothing about Design Thinking and the challenges they have been given to crafting prototypes and presenting them to our partners. These took a great deal of time and effort to be able to quickly absorb the environment, the practical skills us teaching staff will be teaching them but most importantly, to understand the situation our partners have presented to them fully and think hard about how to help them with what they have gotten.</p>
          <p>For those of us who have had a normal course taken in the university, the norm was always a bit towards passive learning whether in a given settings, students were told what to do or learn in a instructed manner. However, being inside SIGHT we prompt active learning for students to pick up things they have never learned before or not even related to their studies or major at all. This was just the first test of their independence towards solving problems without guidance. The real challenge comes when they have to concretely think about a suitable solution that can potentially help out our partners’ situation and relief them from their pain points. Suffice to say that, for their solution to become useful, it involves students learning
to become observant and empathetic. Because there should be thoughts and cares given to the design of their solutions no matter it involves software or hardware, eventually when their solutions or prototypes goes into the hands of our partner, how easily it can be adopted, and use is greatly reflected on the helpfulness of the students’ ideas. In our day-to-day life we
may not face the difficulties like those who are less fortunate than us and without being able to empathize with them, we can only make assumptions that might misjudge the audience’s capacity and economic freedom to utilize the solution.</p>
          <p>The beauty of a design is shown from the appreciation of its users, because whenever parts of a solution or prototype are being praised or continuously used, it means the thoughts and attention to details that goes into the design are actually touching the lives of those people the students have helped.</p>
        </article>
      </section>
    </Layout>
  )
}