name: Publish Image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          if [ ${{ github.ref }} != 'refs/heads/main' ]; then
            TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed 's/\//-/g')
            echo "tag=$TAG" >> "$GITHUB_OUTPUT"
            echo "version=${{ github.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
            echo "version=$(date '+%Y.%m.${{ github.run_number }}')" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image (Production)
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (Default)
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
